package com.android.hospital.ui.theme

import androidx.compose.ui.graphics.Color

/*Dark Default*/
val BackgroundDark = Color(0xFF404040)
val PrimaryDark = Color(0xFF1DE9B6)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)
/*Dark Default*/

/*Light Default*/
val BackgroundLight = Color(0xFFD8D8D8)
val PrimaryLight = Color(0XFF1C7378)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)
/*Light Default*/

/*Patient Light*/
val patient_light_primary = Color(0xFF006D40)
val patient_light_onPrimary = Color(0xFFFFFFFF)
val patient_light_primaryContainer = Color(0xFF94F7BA)
val patient_light_onPrimaryContainer = Color(0xFF002110)
val patient_light_secondary = Color(0xFF4E6354)
val patient_light_onSecondary = Color(0xFFFFFFFF)
val patient_light_secondaryContainer = Color(0xFFD1E8D5)
val patient_light_onSecondaryContainer = Color(0xFF0C1F14)
val patient_light_tertiary = Color(0xFF006E2C)
val patient_light_onTertiary = Color(0xFFFFFFFF)
val patient_light_tertiaryContainer = Color(0xFF68FF8A)
val patient_light_onTertiaryContainer = Color(0xFF002108)
val patient_light_error = Color(0xFFBA1A1A)
val patient_light_errorContainer = Color(0xFFFFDAD6)
val patient_light_onError = Color(0xFFFFFFFF)
val patient_light_onErrorContainer = Color(0xFF410002)
val patient_light_background = Color(0xFFFBFDF8)
val patient_light_onBackground = Color(0xFF191C1A)
val patient_light_surface = Color(0xFFFBFDF8)
val patient_light_onSurface = Color(0xFF191C1A)
val patient_light_surfaceVariant = Color(0xFFDCE5DB)
val patient_light_onSurfaceVariant = Color(0xFF414942)
val patient_light_outline = Color(0xFF717972)
val patient_light_inverseOnSurface = Color(0xFFF0F1EC)
val patient_light_inverseSurface = Color(0xFF2E312E)
val patient_light_inversePrimary = Color(0xFF78DA9F)
val patient_light_surfaceTint = Color(0xFF006D40)
val patient_light_outlineVariant = Color(0xFFC0C9C0)
val patient_light_scrim = Color(0xFF000000)
/*Patient Light*/

/*Patient Dark*/
val patient_dark_primary = Color(0xFF78DA9F)
val patient_dark_onPrimary = Color(0xFF00391F)
val patient_dark_primaryContainer = Color(0xFF00522F)
val patient_dark_onPrimaryContainer = Color(0xFF94F7BA)
val patient_dark_secondary = Color(0xFFB5CCBA)
val patient_dark_onSecondary = Color(0xFF213528)
val patient_dark_secondaryContainer = Color(0xFF374B3D)
val patient_dark_onSecondaryContainer = Color(0xFFD1E8D5)
val patient_dark_tertiary = Color(0xFF3FE26E)
val patient_dark_onTertiary = Color(0xFF003913)
val patient_dark_tertiaryContainer = Color(0xFF00531F)
val patient_dark_onTertiaryContainer = Color(0xFF68FF8A)
val patient_dark_error = Color(0xFFFFB4AB)
val patient_dark_errorContainer = Color(0xFF93000A)
val patient_dark_onError = Color(0xFF690005)
val patient_dark_onErrorContainer = Color(0xFFFFDAD6)
val patient_dark_background = Color(0xFF191C1A)
val patient_dark_onBackground = Color(0xFFE1E3DE)
val patient_dark_surface = Color(0xFF191C1A)
val patient_dark_onSurface = Color(0xFFE1E3DE)
val patient_dark_surfaceVariant = Color(0xFF414942)
val patient_dark_onSurfaceVariant = Color(0xFFC0C9C0)
val patient_dark_outline = Color(0xFF8A938B)
val patient_dark_inverseOnSurface = Color(0xFF191C1A)
val patient_dark_inverseSurface = Color(0xFFE1E3DE)
val patient_dark_inversePrimary = Color(0xFF006D40)
val patient_dark_surfaceTint = Color(0xFF78DA9F)
val patient_dark_outlineVariant = Color(0xFF414942)
val patient_dark_scrim = Color(0xFF000000)
/*Patient Dark*/

/*Doctor light*/
val doctor_light_primary = Color(0xFF00658D)
val doctor_light_onPrimary = Color(0xFFFFFFFF)
val doctor_light_primaryContainer = Color(0xFFC6E7FF)
val doctor_light_onPrimaryContainer = Color(0xFF001E2D)
val doctor_light_secondary = Color(0xFF4F616D)
val doctor_light_onSecondary = Color(0xFFFFFFFF)
val doctor_light_secondaryContainer = Color(0xFFD2E5F4)
val doctor_light_onSecondaryContainer = Color(0xFF0A1D28)
val doctor_light_tertiary = Color(0xFF00658D)
val doctor_light_onTertiary = Color(0xFFFFFFFF)
val doctor_light_tertiaryContainer = Color(0xFFC6E7FF)
val doctor_light_onTertiaryContainer = Color(0xFF001E2D)
val doctor_light_error = Color(0xFFBA1A1A)
val doctor_light_errorContainer = Color(0xFFFFDAD6)
val doctor_light_onError = Color(0xFFFFFFFF)
val doctor_light_onErrorContainer = Color(0xFF410002)
val doctor_light_background = Color(0xFFFBFCFF)
val doctor_light_onBackground = Color(0xFF191C1E)
val doctor_light_surface = Color(0xFFFBFCFF)
val doctor_light_onSurface = Color(0xFF191C1E)
val doctor_light_surfaceVariant = Color(0xFFDDE3EA)
val doctor_light_onSurfaceVariant = Color(0xFF41484D)
val doctor_light_outline = Color(0xFF71787E)
val doctor_light_inverseOnSurface = Color(0xFFF0F1F3)
val doctor_light_inverseSurface = Color(0xFF2E3133)
val doctor_light_inversePrimary = Color(0xFF81CFFF)
val doctor_light_surfaceTint = Color(0xFF00658D)
val doctor_light_outlineVariant = Color(0xFFC1C7CE)
val doctor_light_scrim = Color(0xFF000000)
/*Doctor light*/

/*Doctor dark*/
val doctor_dark_primary = Color(0xFF81CFFF)
val doctor_dark_onPrimary = Color(0xFF00344B)
val doctor_dark_primaryContainer = Color(0xFF004C6B)
val doctor_dark_onPrimaryContainer = Color(0xFFC6E7FF)
val doctor_dark_secondary = Color(0xFFB6C9D8)
val doctor_dark_onSecondary = Color(0xFF21333E)
val doctor_dark_secondaryContainer = Color(0xFF374955)
val doctor_dark_onSecondaryContainer = Color(0xFFD2E5F4)
val doctor_dark_tertiary = Color(0xFF82CFFF)
val doctor_dark_onTertiary = Color(0xFF00344B)
val doctor_dark_tertiaryContainer = Color(0xFF004C6B)
val doctor_dark_onTertiaryContainer = Color(0xFFC6E7FF)
val doctor_dark_error = Color(0xFFFFB4AB)
val doctor_dark_errorContainer = Color(0xFF93000A)
val doctor_dark_onError = Color(0xFF690005)
val doctor_dark_onErrorContainer = Color(0xFFFFDAD6)
val doctor_dark_background = Color(0xFF191C1E)
val doctor_dark_onBackground = Color(0xFFE2E2E5)
val doctor_dark_surface = Color(0xFF191C1E)
val doctor_dark_onSurface = Color(0xFFE2E2E5)
val doctor_dark_surfaceVariant = Color(0xFF41484D)
val doctor_dark_onSurfaceVariant = Color(0xFFC1C7CE)
val doctor_dark_outline = Color(0xFF8B9298)
val doctor_dark_inverseOnSurface = Color(0xFF191C1E)
val doctor_dark_inverseSurface = Color(0xFFE2E2E5)
val doctor_dark_inversePrimary = Color(0xFF00658D)
val doctor_dark_surfaceTint = Color(0xFF81CFFF)
val doctor_dark_outlineVariant = Color(0xFF41484D)
val doctor_dark_scrim = Color(0xFF000000)
/*Doctor dark*/

/*Receptionist*/
val receptionist_light_primary = Color(0xFF626100)
val receptionist_light_onPrimary = Color(0xFFFFFFFF)
val receptionist_light_primaryContainer = Color(0xFFEBE949)
val receptionist_light_onPrimaryContainer = Color(0xFF1D1D00)
val receptionist_light_secondary = Color(0xFF715D00)
val receptionist_light_onSecondary = Color(0xFFFFFFFF)
val receptionist_light_secondaryContainer = Color(0xFFFFE178)
val receptionist_light_onSecondaryContainer = Color(0xFF231B00)
val receptionist_light_tertiary = Color(0xFF6D5E00)
val receptionist_light_onTertiary = Color(0xFFFFFFFF)
val receptionist_light_tertiaryContainer = Color(0xFFFFE247)
val receptionist_light_onTertiaryContainer = Color(0xFF211B00)
val receptionist_light_error = Color(0xFFBA1A1A)
val receptionist_light_errorContainer = Color(0xFFFFDAD6)
val receptionist_light_onError = Color(0xFFFFFFFF)
val receptionist_light_onErrorContainer = Color(0xFF410002)
val receptionist_light_background = Color(0xFFFFFBFF)
val receptionist_light_onBackground = Color(0xFF1C1C17)
val receptionist_light_surface = Color(0xFFFFFBFF)
val receptionist_light_onSurface = Color(0xFF1C1C17)
val receptionist_light_surfaceVariant = Color(0xFFE6E3D1)
val receptionist_light_onSurfaceVariant = Color(0xFF48473A)
val receptionist_light_outline = Color(0xFF797869)
val receptionist_light_inverseOnSurface = Color(0xFFF4F0E7)
val receptionist_light_inverseSurface = Color(0xFF31312B)
val receptionist_light_inversePrimary = Color(0xFFCECC2D)
val receptionist_light_surfaceTint = Color(0xFF626100)
val receptionist_light_outlineVariant = Color(0xFFCAC7B6)
val receptionist_light_scrim = Color(0xFF000000)
/*Receptionist*/

val receptionist_dark_primary = Color(0xFFCECC2D)
val receptionist_dark_onPrimary = Color(0xFF333200)
val receptionist_dark_primaryContainer = Color(0xFF4A4900)
val receptionist_dark_onPrimaryContainer = Color(0xFFEBE949)
val receptionist_dark_secondary = Color(0xFFE5C44A)
val receptionist_dark_onSecondary = Color(0xFF3B2F00)
val receptionist_dark_secondaryContainer = Color(0xFF554500)
val receptionist_dark_onSecondaryContainer = Color(0xFFFFE178)
val receptionist_dark_tertiary = Color(0xFFE3C600)
val receptionist_dark_onTertiary = Color(0xFF393000)
val receptionist_dark_tertiaryContainer = Color(0xFF524600)
val receptionist_dark_onTertiaryContainer = Color(0xFFFFE247)
val receptionist_dark_error = Color(0xFFFFB4AB)
val receptionist_dark_errorContainer = Color(0xFF93000A)
val receptionist_dark_onError = Color(0xFF690005)
val receptionist_dark_onErrorContainer = Color(0xFFFFDAD6)
val receptionist_dark_background = Color(0xFF1C1C17)
val receptionist_dark_onBackground = Color(0xFFE6E2D9)
val receptionist_dark_surface = Color(0xFF1C1C17)
val receptionist_dark_onSurface = Color(0xFFE6E2D9)
val receptionist_dark_surfaceVariant = Color(0xFF48473A)
val receptionist_dark_onSurfaceVariant = Color(0xFFCAC7B6)
val receptionist_dark_outline = Color(0xFF939181)
val receptionist_dark_inverseOnSurface = Color(0xFF1C1C17)
val receptionist_dark_inverseSurface = Color(0xFFE6E2D9)
val receptionist_dark_inversePrimary = Color(0xFF626100)
val receptionist_dark_surfaceTint = Color(0xFFCECC2D)
val receptionist_dark_outlineVariant = Color(0xFF48473A)
val receptionist_dark_scrim = Color(0xFF000000)